# Generated by Django 5.1.1 on 2024-10-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='title',
        ),
    ]
