# Generated by Django 4.0.4 on 2024-08-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='origin_language',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés'), ('FR', 'Frances')], default='EN', max_length=2),
        ),
    ]
