# Generated by Django 5.1.1 on 2024-10-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0011_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
