# Generated by Django 5.1.1 on 2024-10-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0012_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
